/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanime;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author Kaneki
 */
public class DataAnime extends javax.swing.JFrame {

    /**
     * Creates new form DataAnime
     */
    public DataAnime() {
        initComponents();
        refresh();
        txtId.setVisible(false);
    }
    
    private void ambilData() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("ID");
        tbl.addColumn("Judul");
        tbl.addColumn("Tipe");
        tbl.addColumn("Episode");
        tbl.addColumn("Genre");
        tbl.addColumn("Status");
        tbl.addColumn("Rating");
        table_anime.setModel(tbl);
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from data_anime");
            int index = 1;
            while (res.next())
            {
                tbl.addRow(new Object []{
                    index,
                    res.getString("id"),
                    res.getString("judul"),
                    res.getString("tipe"),
                    res.getString("episode"),
                    res.getString("genre"),
                    res.getString("status"),
                    res.getString("rating"),
                });
                table_anime.setModel(tbl);
                index++;
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal Mengambil Data: " + e.getMessage());
        }
    }
    
    private void refresh()
    {
        txtId.setText("");
        txtJudul.setText("");
        txtTipe.setText("");
        txtEpisode.setText("");
        txtGenre.setText("");
        cmbStatus.setSelectedItem("Selesai");
        txtRating.setText("");
        txtCari.setText("");
        txtJudul.requestFocus();
        
        ambilData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_anime = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        txtTipe = new javax.swing.JTextField();
        txtEpisode = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_anime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        table_anime.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table_anime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_animeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_anime);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 31, 1218, 336));

        txtCari.setToolTipText("");
        txtCari.setName("Judul"); // NOI18N
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 404, 297, 33));
        txtCari.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txtTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 470, 146, 33));
        getContentPane().add(txtEpisode, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 534, 90, 33));
        getContentPane().add(txtRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 534, 89, 33));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selesai", "Belum Selesai" }));
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 470, -1, 28));

        jLabel1.setText("Judul");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 388, 42, -1));

        jLabel2.setText("Tipe");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 455, 42, -1));

        jLabel3.setText("Episode");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 514, 102, -1));

        jLabel4.setText("Genre");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 586, 42, -1));

        jLabel5.setText("Status");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 455, 42, -1));

        jLabel6.setText("Rating");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 516, 42, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 385, 27, -1));

        txtGenre.setToolTipText("");
        txtGenre.setName("Judul"); // NOI18N
        getContentPane().add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 606, 482, 33));

        txtJudul.setToolTipText("");
        txtJudul.setName("Judul"); // NOI18N
        getContentPane().add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 404, 482, 33));

        btnCari.setText("Search");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 404, 89, 33));

        btnNew.setText("Refresh");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 606, 106, 33));

        btnSimpan.setText("Create");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 606, 106, 33));

        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 606, 106, 33));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 606, 106, 33));

        btnKeluar.setText("Exit");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1178, 606, 106, 33));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1710, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -10, 1710, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_animeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_animeMouseClicked
        int i = table_anime.getSelectedRow();
        if (i == -1){
                return;
        }
        String id = (String) table_anime.getValueAt(i, 1);
	txtId.setText(id);
	String judul = (String) table_anime.getValueAt(i, 2);
	txtJudul.setText(judul);
	String tipe = (String) table_anime.getValueAt(i, 3);
	txtTipe.setText(tipe);
        String episode = (String) table_anime.getValueAt(i, 4);
	txtEpisode.setText(episode);
        String genre = (String) table_anime.getValueAt(i, 5);
	txtGenre.setText(genre);
	String status = (String) table_anime.getValueAt(i, 6);
	cmbStatus.setSelectedItem(status);
	String rating = (String) table_anime.getValueAt(i, 7);
	txtRating.setText(rating);
    }//GEN-LAST:event_table_animeMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        refresh();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
          if(!txtId.getText().equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Silahkan refresh terlebih dahulu!");
        }
        else{
            String judul = txtJudul.getText();
            String tipe = txtTipe.getText();
            String episode = txtEpisode.getText();
            String genre = txtGenre.getText();
            String status = (String) cmbStatus.getSelectedItem();
            String rating = txtRating.getText();

            try{
                Statement statement = (Statement) koneksi.getConnection().createStatement();
                statement.executeUpdate("insert into data_anime VALUES (null, '" + judul + "','" 
                            + tipe +"','"+ episode +"','"+ genre +"','"+ status +"','"+ rating +"')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");

                refresh();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(txtId.getText().equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Silahkan pilih terlebih dahulu data film yang akan dihapus!");
        }
        else{
            String id = txtId.getText();
            
            try{
                Statement statement = (Statement) koneksi.getConnection().createStatement();
                statement.executeUpdate("delete from data_anime where id = '" + id + "'");
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                
                refresh();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal di Hapus: " + e.getMessage());
            }
        }        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(txtId.getText().equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Silahkan pilih terlebih dahulu data film yang akan  diupdate!");
        }
        else{
            String id = txtId.getText();
            String judul = txtJudul.getText();
            String tipe = txtTipe.getText();
            String episode = txtEpisode.getText();
            String genre = txtGenre.getText();
            String status = (String) cmbStatus.getSelectedItem();
            String rating = txtRating.getText();

            try{
                Statement statement = (Statement) koneksi.getConnection().createStatement();
                statement.executeUpdate("update data_anime SET judul='"+judul+"'," + "tipe='"+tipe+"',"
                        + "episode='"+episode+"'," + "genre='"+genre+"'," + "status='"+status+"',"
                                + "rating='"+rating+"' " + "WHERE id = '"+id+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil diubah");

                refresh();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal diubah: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from data_anime where "
                    + "judul like'%" + txtCari.getText() + "%'");
            DefaultTableModel tbl = new DefaultTableModel();
                tbl.addColumn("#");
                tbl.addColumn("ID");
                tbl.addColumn("Judul");
                tbl.addColumn("Tipe");
                tbl.addColumn("Episode");
                tbl.addColumn("Genre");
                tbl.addColumn("Status");
                tbl.addColumn("Rating");
                
                table_anime.setModel(tbl);
                
                int index = 1;
                while (res.next()){
                    tbl.addRow(new Object[]{
                        index,
                        res.getString("id"),
                        res.getString("judul"),
                        res.getString("tipe"),
                        res.getString("episode"),
                        res.getString("genre"),
                        res.getString("status"),
                        res.getString("rating"),
                    });
                    table_anime.setModel(tbl);
                    index++;
                }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal mencari: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataAnime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_anime;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEpisode;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtTipe;
    // End of variables declaration//GEN-END:variables
}
